import { Header } from "@/components/global/header/header";
import React from "react";

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Bingo Generater",
  description: "Generated by create next app",
};

export default function GeneratorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col h-dvh bg-generator overflow-hidden bg-[url('/images/generator-bg.svg')] bg-cover">
      <Header />
      {children}
    </div>
  );
}
