import type { Metadata } from "next";
import "@styles/global.css";
import { Header } from "@/components/dashboard/header/header";
import { ScreenHeader } from "@/components/dashboard/header/screenHeader";


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="bg-light-gray h-dvh">
      <Header />
      {children}
    </div>
  );
}
