import type { Metadata } from "next";
import "@styles/global.css";
import localFont from "next/font/local";
import Image from "next/image";
import cardsImage from "../public/images/cards.png";

const recoleta = localFont({
  src: [
    { path: "../public/fonts/recoleta-light.woff2", weight: "300", style: "normal" },
    { path: "../public/fonts/recoleta-regular.woff2", weight: "400", style: "normal" },
    { path: "../public/fonts/recoleta-medium.woff2", weight: "500", style: "normal" },
    { path: "../public/fonts/recoleta-semibold.woff2", weight: "600", style: "normal" },
    { path: "../public/fonts/recoleta-bold.woff2", weight: "700", style: "normal" },
    { path: "../public/fonts/recoleta-black.woff2", weight: "900", style: "normal" },
  ],
  variable: "--font-recoleta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bingo SignUp Form",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className={recoleta.variable}>
      <body className="antialiased">
        {/* <section className="min-h-screen grid grid-cols-1 lg:grid-cols-2"> */}
          <div className="grid min-h-svh lg:grid-cols-2">
            <div className="flex flex-col gap-4 p-6">
              <div className="flex flex-1 items-center justify-center">
                <div className="w-full max-w-xs">
                  {children}
                </div>
              </div>
            </div>
            <div className="bg-blue-50 relative hidden lg:block">
              <Image
                src={cardsImage}
                alt="Image"
                className="absolute inset-0 h-full w-full object-cover dark:brightness-[0.2] dark:grayscale"
              />
            </div>
          </div>
        {/* </section> */}
      </body>
    </html>
  );
}
