import type { Metadata } from "next";
import "@styles/global.css";
import { ScreenHeader } from "@/components/dashboard/header/screenHeader";
import { Sidebar, SidebarContent, SidebarGroup, SidebarGroupLabel, SidebarGroupContent, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarProvider } from "@/components/ui/sidebar";
import { Blend, User, CreditCard, SwatchBook } from "lucide-react"


// Menu items.
const items = [
  {
    title: "My Account",
    url: "#",
    icon: User,
  },
  {
    title: "Billing",
    url: "#",
    icon: CreditCard,
  },
  {
    title: "Integration",
    url: "#",
    icon: Blend,
  },
  {
    title: "Appearance",
    url: "#",
    icon: SwatchBook,
  },
]

export const metadata: Metadata = {
  title: "Settings",
  description: "Generated by create next app",
};

export default function SettingsLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div>
      <ScreenHeader
        title="Settings"
        description="Manage your account settings."
      >
      </ScreenHeader>

      <div className="py-8">
        <div className="dashboard-container">

          <SidebarProvider>
            <div className="flex gap-8">

              <Sidebar className="relative">
                <SidebarContent>
                  <SidebarGroup>
                    <SidebarGroupContent>
                      <SidebarMenu>
                        {items.map((item) => (
                          <SidebarMenuItem key={item.title}>
                            <SidebarMenuButton asChild>
                              <a href={item.url}>
                                <item.icon />
                                <span>{item.title}</span>
                              </a>
                            </SidebarMenuButton>
                          </SidebarMenuItem>
                        ))}
                      </SidebarMenu>
                    </SidebarGroupContent>
                  </SidebarGroup>
                </SidebarContent>
              </Sidebar>

              <div className="w-full lg:max-w-150">
                {children}
              </div>

            </div>
          </SidebarProvider>

        </div>
      </div>
    </div>
  );
}
