import type { Metadata } from "next";
import "@styles/global.css";
import { Blend, User, CreditCard, SwatchBook } from "lucide-react";
import Link from "next/link";
import { SITE_URLS } from "@/utils/const";
import { cn } from "@/lib/utils";
import { buttonVariants } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Settings",
  description: "Generated by create next app",
};

export default function SettingsLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div>
      <div className="py-8">
        <div className="dashboard-container">
          <div className="flex items-start flex-wrap gap-10 lg:gap-12">
            <div className="flex-col gap-1 max-w-64 w-full hidden lg:flex">
              <Link
                href={SITE_URLS.account}
                className={cn(buttonVariants({ variant: "ghost", size: "lg" }), "text-sm justify-start")}
              >
                <User />
                Account
              </Link>
              <Link
                href={SITE_URLS.billing}
                className={cn(buttonVariants({ variant: "ghost", size: "lg" }), "text-sm justify-start")}
              >
                <CreditCard />
                Billing
              </Link>
              <Link
                href={SITE_URLS.integrations}
                className={cn(buttonVariants({ variant: "ghost", size: "lg" }), "text-sm justify-start")}
              >
                <Blend />
                Integrations
              </Link>
              <Link
                href={SITE_URLS.appearance}
                className={cn(buttonVariants({ variant: "ghost", size: "lg" }), "text-sm justify-start")}
              >
                <SwatchBook />
                Appearance
              </Link>
            </div>

            {/* <div> */}
              {children}
            {/* </div> */}
          </div>
        </div>
      </div>
    </div>
  );
}
