import { Footer } from "@/components/global/footer/footer";
import { Header } from "@/components/global/header/header";
import React from "react";

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Bingo Template",
  description: "Generated by create next app",
};

export default function TemplatesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <main>
      // <div className="max-w-7xl mx-auto px-6">
        <div>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </div>
      // </div>
    // </main>
  );
}
