import { Footer } from "@/components/global/footer/footer";
import { Header } from "@/components/global/header/header";
import React from "react";

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Bingo Template",
  description: "Generated by create next app",
};

export default function TemplatesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <main className="font-inter">
        {children}
      </main>
      <Footer />
    </>
  );
}
