import type { Metadata } from "next";
import "@styles/global.css";
import Image from "next/image";
import cardsImage from "../../public/images/cards.png";

export const metadata: Metadata = {
  title: "Bingo forms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <main className="flex h-dvh bg-background">
      <div className="flex flex-1 m-6 gap-6">
        <div className="flex flex-1 flex-col justify-center w-1/2 overflow-y-auto">
          <div className="w-full max-w-90 mx-auto">{children}</div>
        </div>
        <div className="relative hidden flex-auto lg:flex lg:items-center z-0 overflow-hidden justify-end bg-blue-50 rounded-14px border border-primary-border">
          <Image
            src={cardsImage}
            alt="Image"
            className="absolute inset-0 h-full w-full object-cover dark:brightness-[0.2] dark:grayscale rounded-14px"
          />
        </div>
      </div>
    </main>
  );
}
