import type { Metadata } from "next";
import "@styles/global.css";
import localFont from "next/font/local";
import Image from "next/image";
import cardsImage from "../../public/images/cards.png";

const recoleta = localFont({
  src: [
    { path: "../../public/fonts/recoleta-light.woff2", weight: "300", style: "normal" },
    { path: "../../public/fonts/recoleta-regular.woff2", weight: "400", style: "normal" },
    { path: "../../public/fonts/recoleta-medium.woff2", weight: "500", style: "normal" },
    { path: "../../public/fonts/recoleta-semibold.woff2", weight: "600", style: "normal" },
    { path: "../../public/fonts/recoleta-bold.woff2", weight: "700", style: "normal" },
    { path: "../../public/fonts/recoleta-black.woff2", weight: "900", style: "normal" },
  ],
  variable: "--font-recoleta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bingo forms",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <main className="flex h-dvh bg-background">
      <div className="flex flex-1 m-6 gap-6">
        <div className="flex flex-1 flex-col justify-center w-1/2 overflow-y-auto">
          <div className="w-full max-w-[360px] mx-auto">
            {children}
          </div>
        </div>
        <div className="relative hidden flex-auto lg:flex lg:items-center z-0 overflow-hidden justify-end">
          <Image
            src={cardsImage}
            alt="Image"
            className="absolute inset-0 h-full w-full object-cover dark:brightness-[0.2] dark:grayscale rounded-4xl"
          />
        </div>
      </div>
    </main>
  );
}
